dist: focal
language: python
  
install:
    - pip install pelican
    - pip install minchin.pelican.plugins.cname
    - pip install markdown

script:
  - pelican content
  
deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main