dist: focal
language: python
  
install:
    - pip install pelican
    - pip install minchin.pelican.plugins.cname
    - pip install markdown

script:
  - "printf \"title: SLRB\ndate: $(date -I)\n\n\" | cat - README.md > content/index.md"
  - pelican content
  - echo "www.slrb.net" > output/CNAME
  
deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
