dist: focal
language: python
  
install:
    - pip install pelican
    - pip install minchin.pelican.plugins.cname
    - pip install markdown
    - pip install beautifulsoup4

script:
  - pelican content -t slrbtheme
  - "cp output/pages/home.html output/index.html"
  - "cp google53ea94da590eb186.html output/"
  - echo "www.slrb.net" > output/CNAME
  
deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
