language: python

before-install:
  - pip install pelican

script:
  - pelican content
  
deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main