# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: sudo pip install pelican markdown ghp-import
      - name: Build
        run: |
          pelican content -t slrbtheme
          "cp output/pages/home.html output/index.html"
          "cp google53ea94da590eb186.html output/"
          "cp sitemap.xml output/"
          echo "www.slrb.net" > output/CNAME
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
